- day2/challenges/challenge-4.md
- day2/challenges/challenge-bo-1.md
- Fixed names of resource groups in day 2 to match instructions
- Fixed git clone instructions to point to azuredevcollege repository
> Fixed some typos

- .vuepress/config.yml
Enable sidebar navigation for the vuepress page.
> Configure vuepress to include meaningful sidebar

- day3/apps/infrastructure/templates/scm-resources-api-dotnetcore.json
- day3/apps/infrastructure/templates/scm-search-api-dotnetcore.json
- day3/apps/infrastructure/templates/scm-textanalytics-nodejs-infra.json
- day5/apps/infrastructure/templates/scm-resources-api-dotnetcore.json
- day5/apps/infrastructure/templates/scm-search-api-dotnetcore.json
added WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and function runtime v3
- added WEBSITE_CONTENTAZUREFILECONNECTIONSTRING to function's app settings for all dotnetcore functions
- use function runtime ~3 in TextAnalytics Function
> Fix ARM Template deployment settings

- day1/README.md
- day1/challenges/Challenge10/Challenge10Start.json
- day1/challenges/Challenge10/challenge-10.md
- day1/challenges/Challenge6/challenge-6.md
- day1/challenges/Challenge7/Challenge7Start.json
- day1/challenges/Challenge7/challenge-7.md
- day1/challenges/Challenge8/Challenge8Start.json
- day1/challenges/Challenge8/challenge-8.md
- day1/challenges/Challenge9/Challenge9Start.json
- day1/challenges/Challenge9/challenge-9.md
> Day1changes

- day4/challenges/challenge-3.md
Add pipeline.yaml to include paths to trigger consecutive builds.
> Update day4 challenge 3

- day7/terraform/kubernetes/main.tf
K8s version aus dem terraform file ist nicht mehr provisionierbar gewesen.
> Autodetect latest kubernetes patch version

- day5/challenges/challenge-3.md
- day5/challenges/challenge-bo-1.md
SCM Frontend is deployed with AAD integration directly after the deployment of the SCM Contacts API
> Day5 documentation and deployment order

- day5/apps/checkpoint/.terraform.lock.hcl
- day5/apps/checkpoint/main.tf
- day5/apps/checkpoint/versions.tf
Now updated for terraform v0.14.3
> Update terraform checkpoint for day 5

- day4/challenges/challenge-5.md
Sample PR for day4 demo. Please leave open.
> Fix typo in day4 challenge 5

- day5/challenges/challenge-bo-1.md
Stage Production should be Testing
> Typo: Stage Production -> Testing

- day1/challenge-06/README.md
`SAS Url` should be `SAS token`
> Fixed typo (SAS Url to SAS token)

- day3/challenges/challenge-1.md
> Revise note about single logical partition upper storage limit

- day1/challenge-09/challengestart/challengestart.json
> adding dependency VNET before NIC to challenge 9

- day7/challenges/challenge-0.md
- day7/challenges/challenge-1.md
- day7/challenges/challenge-2.md
- day7/challenges/challenge-3.md
- day7/challenges/challenge-4.md
This PR addresses a couple of typos in the day7 chapter. No changes to content besides fixing typos have been made.
> fixed typos in k8s day7

- day7/challenges/challenge-4.md
... with a local variable
By simply defining a shell variable `ACR_NAME` that is used througout every `az acr build` - and reducing the massive `cd xyz` and replacing work, which isn't needed to understand AKS :)
> Replace need to cd into every single app's dir & replace `<ACR_NAME>`

- day1/challenge-10/challengestart/challengestart.json
- day1/challenge-11/challengestart/challengestart.json
This pull request contains the correction of the two file paths for day 1 challenge 10 and 11 as addressed in issue #164
> Correction of paths to zip files for Day1

- day1/challenge-10/challengestart/challengestart.json
#122 
adding a random fqdn to lb as some users are not allowed to browse ip addresses.
> #122 adding DNS to challenge 10 ARM template

- .github/workflows/day4-scm-resourcesapi.yml
Reverts azuredevcollege/trainingdays#250
> Revert "Set environments for all deploy jobs"

- .github/workflows/day5-scm-frontend.yml
- day5/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.Api/Adc.Scm.Resources.Api.csproj
- day5/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.Api/packages.lock.json
- day5/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.ImageResizer/Adc.Scm.Resources.ImageResizer.csproj
- day5/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.ImageResizer/packages.lock.json
- day5/apps/dotnetcore/Scm.Search/Adc.Scm.Search.Api/Adc.Scm.Search.Api.csproj
- day5/apps/dotnetcore/Scm.Search/Adc.Scm.Search.Api/packages.lock.json
- day5/apps/dotnetcore/Scm.Search/Adc.Scm.Search.Indexer/Adc.Scm.Search.Indexer.csproj
- day5/apps/dotnetcore/Scm.Search/Adc.Scm.Search.Indexer/packages.lock.json
- day5/apps/dotnetcore/Scm/Adc.Scm.Api/Adc.Scm.Api.csproj
- day5/apps/dotnetcore/Scm/Adc.Scm.Api/packages.lock.json
> Fix Frontend patch and use packages.lock.json

- .github/workflows/.pages.yaml
- .vuepress/config.yml
Adds a copy button to all code fences in vuepress.
> Add vuepress-plugin-code-copy

- .github/workflows/.pages.yaml
- .github/workflows/day2-scm-cleanup.yml
- .github/workflows/day3-scm-cleanup.yml
- .github/workflows/day4-scm-cleanup.yml
> Workflows should only run within the azdc organisation

- .github/workflows/day2-scm-common.yml
- .github/workflows/day2-scm-contactsapi.yml
- .github/workflows/day2-scm-fe.yml
- .github/workflows/day2-scm-resourcesapi.yml
- .github/workflows/day3-scm-common.yml
- .github/workflows/day3-scm-contactsapi.yml
- .github/workflows/day3-scm-frontend.yml
- .github/workflows/day3-scm-resourcesapi.yml
- .github/workflows/day3-scm-searchapi.yml
- .github/workflows/day3-scm-visitreports.yml
- .github/workflows/day4-scm-common.yml
- .github/workflows/day4-scm-contactsapi.yml
- .github/workflows/day4-scm-frontend.yml
- .github/workflows/day4-scm-resourcesapi.yml
- .github/workflows/day4-scm-searchapi.yml
- .github/workflows/day4-scm-visitreports.yml
- .github/workflows/day5-scm-common.yml
- .github/workflows/day5-scm-contactsapi.yml
- .github/workflows/day5-scm-frontend.yml
- .github/workflows/day5-scm-resourcesapi.yml
- .github/workflows/day5-scm-searchapi.yml
- .github/workflows/day5-scm-visitreports.yml
Use failOnStdErr: false, as Azure CLI writes some lines to stderr. AzureCLI's exit code is still respected.
closes #279
> Fix arm-deploy action

- .github/workflows/day2-scm-resourcesapi.yml
- .github/workflows/day3-scm-resourcesapi.yml
- .github/workflows/day3-scm-searchapi.yml
- .github/workflows/day4-scm-resourcesapi.yml
- .github/workflows/day4-scm-searchapi.yml
- .github/workflows/day5-scm-resourcesapi.yml
- .github/workflows/day5-scm-searchapi.yml
Sync function triggers after deployment of functions to an consumption plan.
close #282
> Sync function triggers after deployment

- day4/README.md
- day4/challenges/01-challenge-boards.md
- day4/challenges/02-github-actions-intro.md
- day4/challenges/03-challenge-bicep.md
- day4/challenges/04-challenge-azdc-repo.md
- day4/challenges/05-challenge-common-cicd.md
- day4/challenges/06-breakout.md
> Day4 Review and navigation

- README.md
> AzDC README.md

- day4/challenges/03-challenge-bicep.md
- curly bracked added to the beginning of the secret token value at the "Storing the secret" section
> Correction to the day4 challenge 3 file

- day3/scripts/baseline/deploy_baseline.sh
This is a fix for running the deploy_baseline.sh script in a local bash without path issues.
> fix baslinescript for local bash

- day1/challenge-08/challengestart/challengestart.json
- day1/challenge-09/challengestart/challengestart.json
#333 
fixing issue due to path change
> fixing ARM template mispathing

- day4/challenges/01-challenge-boards.md
> fix: fixing typo

- day5/scripts/enable-workflows-for.sh
Usage, from the root of the trainingdays folder:
```shell
day5/scripts/enable-workflows-for.sh <github_username>
```
> Add script to enable workflows

- day6/challenges/challenge4.md
This PR will fix a little typo in Day 6 / challenge-4
> fix typo in Day 6 / challenge-4

- day3/challenges/04-challenge-bo-1.md
This PR links the correct baseline deployment script for day 3, challenge 4, break out 1.
> Day 3 - Fix link to baseline deployment script

- day1/challenge-02/README.md
- day1/challenge-03/README.md
- day1/challenge-04/README.md
- day1/challenge-05/README.md
- day1/challenge-05/challengestart/challengestart.json
- day1/challenge-06/README.md
- day1/challenge-06/challengestart/challengestart.json
- day1/challenge-07/README.md
- day1/challenge-08/README.md
- day1/challenge-08/challengestart/challengestart.json
- day1/challenge-09/README.md
Some hyperlinks were not yet updated according to the simplification of day 1. Since some challenges changed numbers, references and hyperlinks needed to be updated.
> Edit wrong hyperlinks in day1
